#pragma once

#ifndef PEBMONITOR_KERNEL_SHARED
#include <windows.h>
#include <winioctl.h>
#endif

#define MAX_RULE_LENGTH 256
#define MAX_RULE_ID_LENGTH 128
#define MAX_REG_PATH_LENGTH 512
#define MAX_REGISTRY_RULE_COUNT 256
#define MAX_FILE_RULE_COUNT 256

#define PEB_MONITOR_DEVICE 0x8000
#define IOCTL_GET_DRIVER_EVENT   CTL_CODE(PEB_MONITOR_DEVICE, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ADD_DRIVER_RULE    CTL_CODE(PEB_MONITOR_DEVICE, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_CLEAR_DRIVER_RULES CTL_CODE(PEB_MONITOR_DEVICE, 0x804, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ADD_REGISTRY_RULE  CTL_CODE(PEB_MONITOR_DEVICE, 0x805, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_CLEAR_REGISTRY_RULES CTL_CODE(PEB_MONITOR_DEVICE, 0x806, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ADD_REGISTRY_ALLOW_RULE  CTL_CODE(PEB_MONITOR_DEVICE, 0x807, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_CLEAR_REGISTRY_ALLOW_RULES CTL_CODE(PEB_MONITOR_DEVICE, 0x808, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_QUERY_DRIVER_STATUS CTL_CODE(PEB_MONITOR_DEVICE, 0x809, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_SET_ACTIVE_CONFIG_INFO CTL_CODE(PEB_MONITOR_DEVICE, 0x80A, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_ADD_FILE_RULE CTL_CODE(PEB_MONITOR_DEVICE, 0x80B, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_CLEAR_FILE_RULES CTL_CODE(PEB_MONITOR_DEVICE, 0x80C, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define PEBMONITOR_PROCESS_PORT_NAME L"\\PebMonitorProcessPort"
#define PROCESS_PORT_PROTOCOL_VERSION 3UL
#define PROCESS_PORT_REQUEST_FLAG_FILE_OPEN_NAME_AVAILABLE 0x0001UL
#define PROCESS_VERDICT_TIMEOUT_MS_DEFAULT 1000UL
#define PROCESS_VERDICT_TIMEOUT_MS_MIN 100UL
#define PROCESS_VERDICT_TIMEOUT_MS_MAX 10000UL
#define PROCESS_VERDICT_FAIL_OPEN 1UL
#define PROCESS_VERDICT_FAIL_CLOSE 2UL

#define DRIVER_STATUS_FLAG_DEVICE_READY 0x0001UL
#define DRIVER_STATUS_FLAG_PROCESS_CALLBACK_REGISTERED 0x0002UL
#define DRIVER_STATUS_FLAG_IMAGE_CALLBACK_REGISTERED 0x0004UL
#define DRIVER_STATUS_FLAG_REGISTRY_CALLBACK_REGISTERED 0x0008UL
#define DRIVER_STATUS_FLAG_FILE_FILTER_READY 0x0010UL
#define DRIVER_STATUS_FLAG_PROCESS_PORT_CONNECTED 0x0020UL

#define DRIVER_EVENT_TYPE_OBSERVED_LOAD   1UL
#define DRIVER_EVENT_TYPE_BLOCKED_SERVICE 2UL
#define DRIVER_EVENT_TYPE_BLOCKED_REGISTRY_OPERATION 3UL
#define DRIVER_EVENT_TYPE_BLOCKED_REGISTRY_SET DRIVER_EVENT_TYPE_BLOCKED_REGISTRY_OPERATION
#define DRIVER_EVENT_TYPE_BLOCKED_FILE_OPERATION 4UL

#define REGISTRY_OPERATION_SET_VALUE 1UL
#define REGISTRY_OPERATION_CREATE_KEY 2UL
#define REGISTRY_OPERATION_DELETE_VALUE 3UL
#define REGISTRY_OPERATION_DELETE_KEY 4UL
#define REGISTRY_OPERATION_RENAME_KEY 5UL
#define REGISTRY_OPERATION_SET_INFORMATION_KEY 6UL

#define REGISTRY_MATCH_FLAG_PROCESS_NAME 0x0001UL
#define REGISTRY_MATCH_FLAG_KEY_PATH     0x0002UL
#define REGISTRY_MATCH_FLAG_VALUE_NAME   0x0004UL
#define REGISTRY_MATCH_FLAG_VALUE_DATA   0x0008UL
#define REGISTRY_MATCH_FLAG_INFO_CLASS   0x0010UL

#define REGISTRY_MATCH_TYPE_EXACT    1UL
#define REGISTRY_MATCH_TYPE_PREFIX   2UL
#define REGISTRY_MATCH_TYPE_SUFFIX   3UL
#define REGISTRY_MATCH_TYPE_CONTAINS 4UL

#define FILE_OPERATION_CREATE 1UL
#define FILE_OPERATION_WRITE 2UL
#define FILE_OPERATION_CREATE_OR_WRITE 3UL

#define FILE_MATCH_FLAG_PROCESS_NAME 0x0001UL
#define FILE_MATCH_FLAG_TARGET_PATH  0x0002UL
#define FILE_MATCH_FLAG_EXTENSION    0x0004UL

typedef struct _PROCESS_PORT_REQUEST {
    ULONG Version;
    ULONG Flags;
    ULONGLONG EventId;
    ULONGLONG CreateTime;
    ULONG ProcessId;
    ULONG ParentProcessId;
    WCHAR ImagePath[MAX_REG_PATH_LENGTH];
    WCHAR ParentImagePath[MAX_REG_PATH_LENGTH];
    WCHAR CommandLine[1024];
    WCHAR ParentCommandLine[1024];
} PROCESS_PORT_REQUEST, *PPROCESS_PORT_REQUEST;

typedef struct _PROCESS_PORT_REPLY {
    ULONG Version;
    ULONG BlockProcess;
} PROCESS_PORT_REPLY, *PPROCESS_PORT_REPLY;

typedef struct _DRIVER_EVENT {
    ULONG EventType;
    ULONG ProcessId;
    ULONG Severity;
    ULONG RegistryOperation;
    ULONG FileOperation;
    WCHAR ProcessName[MAX_RULE_LENGTH];
    WCHAR RuleId[MAX_RULE_ID_LENGTH];
    WCHAR TargetPath[MAX_REG_PATH_LENGTH];
    WCHAR InfoClass[MAX_RULE_LENGTH];
    WCHAR ValueName[MAX_RULE_LENGTH];
    WCHAR ValueData[MAX_RULE_LENGTH];
} DRIVER_EVENT, *PDRIVER_EVENT;

typedef struct _BLACKLIST_RULE {
    WCHAR DriverName[MAX_RULE_LENGTH];
} BLACKLIST_RULE, *PBLACKLIST_RULE;

typedef struct _REGISTRY_RULE {
    ULONG Operation;
    ULONG MatchFlags;
    ULONG Severity;
    ULONG ProcessNameMatchType;
    WCHAR ProcessName[MAX_RULE_LENGTH];
    ULONG KeyPathMatchType;
    WCHAR KeyPath[MAX_REG_PATH_LENGTH];
    ULONG InfoClassMatchType;
    WCHAR InfoClass[MAX_RULE_LENGTH];
    ULONG ValueNameMatchType;
    WCHAR ValueName[MAX_RULE_LENGTH];
    ULONG ValueDataMatchType;
    WCHAR ValueData[MAX_RULE_LENGTH];
    WCHAR RuleId[MAX_RULE_ID_LENGTH];
} REGISTRY_RULE, *PREGISTRY_RULE;

typedef struct _FILE_RULE {
    ULONG Operation;
    ULONG MatchFlags;
    ULONG Severity;
    ULONG ProcessNameMatchType;
    WCHAR ProcessName[MAX_RULE_LENGTH];
    ULONG TargetPathMatchType;
    WCHAR TargetPath[MAX_REG_PATH_LENGTH];
    ULONG ExtensionMatchType;
    WCHAR Extension[MAX_RULE_LENGTH];
    WCHAR RuleId[MAX_RULE_ID_LENGTH];
} FILE_RULE, *PFILE_RULE;

typedef struct _DRIVER_CONFIG_INFO {
    WCHAR ConfigVersion[MAX_RULE_LENGTH];
    WCHAR ProfileName[MAX_RULE_LENGTH];
    WCHAR GeneratedAt[MAX_RULE_LENGTH];
    ULONG ProcessVerdictTimeoutMs;
    ULONG ProcessVerdictFailMode;
} DRIVER_CONFIG_INFO, *PDRIVER_CONFIG_INFO;

typedef struct _DRIVER_RUNTIME_STATUS {
    ULONG StatusFlags;
    ULONG DriverBlacklistCount;
    ULONG FileRuleCount;
    ULONG RegistryRuleCount;
    ULONG RegistryAllowRuleCount;
    ULONG DriverEventQueueCount;
    ULONGLONG ProcessVerdictRequestCount;
    ULONGLONG ProcessVerdictTimeoutCount;
    ULONGLONG ProcessPortConnectCount;
    ULONGLONG ProcessPortDisconnectCount;
    ULONGLONG LastProcessPortConnectTime;
    ULONGLONG LastProcessPortDisconnectTime;
    ULONGLONG LastProcessVerdictTimeoutTime;
    ULONG ProcessVerdictTimeoutMs;
    ULONG ProcessVerdictFailMode;
    WCHAR ConfigVersion[MAX_RULE_LENGTH];
    WCHAR ProfileName[MAX_RULE_LENGTH];
    WCHAR GeneratedAt[MAX_RULE_LENGTH];
} DRIVER_RUNTIME_STATUS, *PDRIVER_RUNTIME_STATUS;
